using Playcoo.Common;
public class SKILL : ConstDataRow<SKILL>
{
	public const int TableID = 12;
	public const int DigitBase = 2;
	public int n_ID;
	public int n_LEVEL_LEARN;
	public string s_ICON;
	public int n_PASSIVE;
	public string s_NAME;
	public int n_SCHOOL;
	public int n_TYPE;
	public int n_FINISH;
	public int n_CD;
	public int n_TARGET;
	public int n_SP;
	public int n_MP;
	public int n_CP;
	public int n_MINRANGE;
	public int n_RANGE;
	public int n_CAST_FX;
	public int n_TAIL_FX;
	public int n_SWING_FX;
	public int n_CASTOUT_TYPE;
	public int n_CASTOUT_FX;
	public int n_HIT_FX;
	public int n_MISSILE_ID;
	public int n_AREA;
	public int n_BUFF;
	public string s_TAG;
	public string s_CONDITION;
	public string s_CAST;
	public string s_CAST_COND;
	public string s_CAST_EFFECT;
	public float f_ATK;
	public float f_DEF;
	public float f_POW;
	public int n_HITBACK;
	public string s_LINK_SKILL;
}
