using Playcoo.Common;
public class STANDARD_MOB : ConstDataRow<STANDARD_MOB>
{
	public const int TableID = 48;
	public const int DigitBase = 5;
	public int n_ID;
	public int n_MOBEXP;
	public int n_SP;
	public int n_HPMAX;
	public int n_RECOVER_HP;
	public int n_STAMINAMAX;
	public int n_RECOVER_STAMINA;
	public int n_SPEED_RUN;
	public int n_STRENGH;
	public int n_CONSITUTION;
	public int n_AGILITY;
	public int n_PERCEPTION;
	public int n_INTELLECT;
	public int n_DAMMIN_PHYSICS;
	public int n_DAMMIN_MAGIC;
	public int n_DAMPLUS_PHYSICS;
	public int n_DAMPLUS_MAGIC;
	public int n_AC_PHYSICS;
	public int n_AC_MAGIC;
	public int n_ABSORB_PHYSICS;
	public int n_ABSORB_MAGIC;
	public int n_PENETRATE_PHYSICS;
	public int n_PENETRATE_MAGIC;
	public float f_ANTI_STUN;
	public float f_STUN;
	public float f_ANTI_CURSE;
	public float f_CURSE;
	public float f_HITRATE;
	public float f_DODGE;
	public float f_POWERHIT;
	public float f_ANTI_POWERHIT;
	public float f_BYPASS;
	public float f_OVERHIT;
	public float f_MULTIPLY_POWERDAM;
	public float f_ABSORB_POWERDAM;
	public float f_ABSORB_SHIELD;
	public float f_BLOCKRATE;
	public float f_MUL_DAMAGE;
}
