using Playcoo.Common;
public class STANDARD_BUFF : ConstDataRow<STANDARD_BUFF>
{
	public const int TableID = 46;
	public const int DigitBase = 5;
	public int n_ID;
	public int n_HPMAX;
	public int n_RECOVER_HP;
	public int n_STAMINAMAX;
	public int n_RECOVER_STAMINA;
	public int n_SPEED_RUN;
	public int n_STRENGH;
	public int n_CONSITUTION;
	public int n_AGILITY;
	public int n_PERCEPTION;
	public int n_INTELLECT;
	public int n_DAMMIN_PHYSICS;
	public int n_DAMMIN_MAGIC;
	public int n_DAMPLUS_PHYSICS;
	public int n_DAMPLUS_MAGIC;
	public int n_AC_PHYSICS;
	public int n_AC_MAGIC;
	public int n_ABSORB_PHYSICS;
	public int n_ABSORB_MAGIC;
	public int n_PENETRATE_PHYSICS;
	public int n_PENETRATE_MAGIC;
	public float f_ANTI_STUN;
	public float f_STUN;
	public float f_ANTI_CURSE;
	public float f_CURSE;
	public float f_HITRATE;
	public float f_DODGE;
	public float f_POWERHIT;
	public float f_ANTI_POWERHIT;
	public float f_BYPASS;
	public float f_OVERHIT;
	public float f_MULTIPLY_POWERDAM;
	public float f_ABSORB_POWERDAM;
	public float f_ABSORB_SHIELD;
	public float f_BLOCKRATE;
	public float f_MUL_DAMAGE;
	public float f_MUL_BURST;
	public float f_MUL_HEALING;
	public float f_MUL_HATE;
	public float f_MUL_RANGE;
	public float f_MUL_DAMAGE_AREA;
	public float f_MUL_CD;
	public float f_MUL_BUFF_DURING;
	public int n_ADD_COST;
	public float f_MUL_COST;
	public float f_SP_ADD_STUN;
	public float f_SP_ADD_CURSE;
	public float f_SP_ADD_HITRATE;
	public float f_SP_ADD_DODGE;
	public float f_SP_ADD_POWERHIT;
	public float f_SP_ADD_BYPASS;
	public float f_SP_ADD_OVERHIT;
	public float f_SP_ADD_BLOCKRATE;
	public float f_SP_ADD_MUL_DAMAGE;
	public float f_SP_ADD_MUL_BURST;
	public float f_SP_ADD_MUL_HEALING;
	public float f_SP_ADD_MUL_HATE;
	public float f_SP_ADD_MUL_RANGE;
	public float f_SP_ADD_MUL_CD;
	public float f_SP_ADD_MUL_BUFF_DURING;
}
